### ISSUE TITLE
Dependency hell in Linux

### ISSUE THREAD

**Issue by soumyaDghosh** [Canny1913/miunlock#15]
Please list out all the necessary dependencies for Linux. Atleast list all for Ubuntu. I am not getting the code worked. Always getting alot of errors.

**Comment by Canny1913** [comment]
https://github.com/Canny1913/miunlock/blob/master/requirements.txt

**Comment by Practicalbutterfly5** [comment]
> Please list out all the necessary dependencies for Linux. Atleast list all for Ubuntu. I am not getting the code worked. Always getting alot of errors.

Did you use python virtual environment? If not it's probably some apt installed python packages interfering

**Comment by sskras** [comment]
No response for one year already.

**Comment by soumyaDghosh** [comment]
Hi, I am extremely sorry about this. I didn't use this again. I will close this, as back then, when I reported this, I knew a very less about Linux. Today, situations have changed a lot. Sorry, for this inconvenience, and also thanks for reminding me.
