### ISSUE TITLE
got pcapng 4u

### ISSUE THREAD

**Issue by CastixGitHub** [Canny1913/miunlock#20]
I got a wireshark dump of the successful unlock of a `selene` redmi 10 model `21061119DG` from windows 10 with the official tool version `6.5.406.31`

the official tool forced me to wait for 90 hours at the first attempt (well after the 15 days quarantine)

referencing #3 #14 maybe #10 and #9

just drop me an email or reply and I'll send you

**Comment by c0m94d3** [comment]
@CastixGitHub c0m94d3[at]proton[dot]me

**Comment by bibi09456** [comment]
@CastixGitHub bibi094@proton.me

**Comment by Canny1913** [comment]
this issue is months old lol (sorry) so i dont think you have the dump anymore

**Comment by bibi09456** [comment]
> this issue is months old lol (sorry) so i dont think you have the dump anymore

i still have the dump
