### ISSUE TITLE
need help. stuck in steps.

### ISSUE THREAD

**Issue by Midnightmadwalk-coder** [Canny1913/miunlock#21]
hi, can anyone help me? i dont understand the next step after python main.py. the result sdays to login to xiaaomi and copy paste the code in code.txt . which i totally dont understaqnd. can anyone please help me out

![Screenshot from 2022-12-24 17-40-39](https://user-images.githubusercontent.com/78001660/209435778-5911f9e1-14ab-4c97-bd45-fca0c46a6ef9.png)

**Comment by helloplauz10** [comment]
That's a error code. Maybe try running the JavaScript again?
