### ISSUE TITLE
Code Throws Error & Only Gives Unlock Time Remaining

### ISSUE THREAD

**Issue by chr0m3chaos** [Canny1913/miunlock#4]
![error](https://user-images.githubusercontent.com/102193212/159593025-8cd15402-e1cf-4713-9d8f-b38384da144a.jpg)
I'm assuming this isn't normal lol. I've tried using the "test", "main", and "1.01" versions of the tool here with the same results.

**Comment by Canny1913** [comment]
Nah it is normal. Since it works the same way as the official MiUnlock does.

**Comment by chr0m3chaos** [comment]
Wait, so am I missing something then? The next step says "if the code succeeds it will give you a really long string which is the unlock token, put this into a file with a hex editor, name it 'token'."

**Comment by Canny1913** [comment]
No you aren't missing anything. When the specified time ends it already unlocks the device for you. Those instructions are for unlocking the device manually if autounlocking doesn't for for some reason.

**Comment by chr0m3chaos** [comment]
Ah, okay. I was under the impression that this was code to sneakily get the unlock token while Xiaomi was making you wait to unlock the bootloader. So this repository is for the people who are having problems with the client that Xiaomi provides for consumers then.  I got it now. Dang, guess I'll be waiting 9 more days then haha.

**Comment by chr0m3chaos** [comment]
That's true! Very cool tool in that case. Keep up the good work :)
