### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RohitVerma882** [Canny1913/miunlock#6]
I'm received token from sever.
How to unlock device using fastboot binary?

I'm tried ```fastboot oem unlock <encrypted data>```

But it does not work.

**Comment by Canny1913** [comment]
![Screenshot_20220528-145057_Chrome](https://user-images.githubusercontent.com/94744045/170824291-233eb3cf-a9b6-4142-bfcc-f787dd3833ef.png)

You can't just copy and paste the code inside fastboot.

**Comment by RohitVermaOP** [comment]
> ![Screenshot_20220528-145057_Chrome](https://user-images.githubusercontent.com/94744045/170824291-233eb3cf-a9b6-4142-bfcc-f787dd3833ef.png)
> 
> You can't just copy and paste the code inside fastboot.

I want to unlock using fastboot binary.
What i need to do?

**Comment by Canny1913** [comment]
> > ![Screenshot_20220528-145057_Chrome](https://user-images.githubusercontent.com/94744045/170824291-233eb3cf-a9b6-4142-bfcc-f787dd3833ef.png)
> > You can't just copy and paste the code inside fastboot.
> 
> I want to unlock using fastboot binary. What i need to do?

Look at the screenshot i sent you. It explains it.

**Comment by RohitVermaOP** [comment]
> > > ![Screenshot_20220528-145057_Chrome](https://user-images.githubusercontent.com/94744045/170824291-233eb3cf-a9b6-4142-bfcc-f787dd3833ef.png)
> > > You can't just copy and paste the code inside fastboot.
> > 
> > 
> > I want to unlock using fastboot binary. What i need to do?
> 
> Look at the screenshot i sent you. It explains it. You need to use fastbrute.

I know bro. But don't have pc or laptop. I'm using termux with modified version of fastboot.

**Comment by RohitVermaOP** [comment]
Any alternative ways to unlock with termux fastboot?

**Comment by RohitVermaOP** [comment]
How fastbrute works and why need this?

**Comment by Canny1913** [comment]
1)Termux can run fastbrute since it's a python script.

2)According to penn5, fastbrute provides a direct communication between the phone and the computer, effectively bypassing any restrictions that normal fastboot protocol has.

You can try "fastboot oem unlock token.bin" instead of fastbrute but i doubt it'll work.

**Comment by RohitVermaOP** [comment]
> 1)Termux can run fastbrute since it's a python script.
> 
> 2)According to penn5, fastbrute provides a direct communication between the phone and the computer, effectively bypassing any restrictions that normal fastboot protocol has.
> 
> You can try "fastboot oem unlock token.bin" instead of fastbrute but i doubt it'll work.

Ok, understand!
Which tool or termux cmd i use for creating token file?

**Comment by Canny1913** [comment]
By the way the unlock took can unlock the device without requiring fastboot. Just keep the device plugged in while it's unlocking.

also make sure you installed python-adb using "python install adb"

As for the tool, just use a standard hex editor from play store.

**Comment by RohitVermaOP** [comment]
> By the way the unlock took can unlock the device without requiring fastboot. Just keep the device plugged in while it's unlocking.
> 
> also make sure you installed python-adb using "python install adb"
> 
> As for the tool, just use a standard hex editor from play store.

I'm sure python-adb will not work on android without root permission!

**Comment by Canny1913** [comment]
Try it and see since i didnt test that one.

**Comment by RohitVermaOP** [comment]
> By the way the unlock took can unlock the device without requiring fastboot. Just keep the device plugged in while it's unlocking and it should ask you "if you want to unlock now"
> 
> also make sure you installed python-adb using "python install adb"
> 
> As for the tool, just use a standard hex editor from play store then create the token file.

And thanks for helping

I will try to modify python-adb or make my own java fastboot protocol

**Comment by RohitVerma882** [comment]
![Screenshot_2022-06-12-17-02-08-95_8981493b86fb4c75a83497c6417d0929](https://user-images.githubusercontent.com/56387351/173240074-558df329-7fd8-4493-9117-321cae442b17.jpg)
I made this, how i can send ```token.bin``` to fastboot device?

**Comment by RohitVerma882** [comment]
How to send ```token.bin``` file using ```download:00001234``` fastboot protocol?

**Comment by RohitVerma882** [comment]
My device is unlocked. 🙂

![Screenshot_2022-06-14-10-08-13-21_7dbb45340add4770918acbcc3569fd45](https://user-images.githubusercontent.com/56387351/173494508-a9e2474e-478d-48a4-ac70-e1be2e7bdbb9.jpg)

I made this fastboot-java sample app to communicate with device directly

**Comment by unfairDude** [comment]
> My device is unlocked. slightly_smiling_face
> 
> ![Screenshot_2022-06-14-10-08-13-21_7dbb45340add4770918acbcc3569fd45](https://user-images.githubusercontent.com/56387351/173494508-a9e2474e-478d-48a4-ac70-e1be2e7bdbb9.jpg)
> 
> I made this fastboot-java sample app to communicate with device directly

lucky you... this tool is patched now and am stuck with linux machine and locked device fuck xiaomi
